# apiVersion: v1
# kind: Pod
# metadata:
#   name: my-first-pod
# spec:
#   containers:
#     - image: nginx:alpine
#       name: first-container-of-pod
#       resources:
#         limits:
#           memory: "512Mi"
#           cpu: "1"


apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment

spec:
  selector:
    matchLabels:
      pod: web
  replicas: 3
  template:
    metadata:
      name: web-pod
      labels:
        pod: web
    spec:
      containers:
        - image: cofa/deployment-training1
          name: test-deployment
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
          ports:
            - containerPort: 80

